apiVersion: v1
kind: Service
metadata:
  name: googly-service
spec:
  selector:
    app: googly-login
  type: {{ .Values.googly.service.type }}
  ports:
    - port: {{ .Values.googly.service.port }}
      targetPort: {{ .Values.googly.service.targetPort }}
      nodePort: {{ .Values.googly.service.nodePort }}
      protocol: TCP
