apiVersion: v1
kind: PersistentVolume
metadata:
  name: googly-postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.pvc.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.postgres.pvc.path }}
