apiVersion: v1
kind: Service
metadata:
  name: googly-service
spec:
  selector:
    app: googly-login
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30110
      protocol: TCP
