apiVersion: apps/v1
kind: Deployment
metadata:
  name: googly-deployment
spec:
  replicas: {{ .Values.googly.replicas }}
  selector:
    matchLabels:
      app: googly-login
  template:
    metadata:
      labels:
        app: googly-login
    spec:
      containers:
        - name: googly-login
          image: {{ .Values.googly.image }}
          ports:
            - containerPort: {{ .Values.googly.service.targetPort }}
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: postgres-secret