apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: POSTGRESQL_CLIENT_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: googly-data


      volumes:
        - name: googly-data
          persistentVolumeClaim:
            claimName: googly-postgres-pvc